### ISSUE TITLE
Feature Req: Randomize source IP and port

### ISSUE THREAD

**Issue by PedroChaparro123** [pktgen/Pktgen-DPDK#341]
Hi!

It'd be very convenient for me to randomize the source IP address and port, to perform firewall general and resource exhaustion testing, and so I was looking for a nice `set`/`enable` command to do that. Would it be possible to alter/add a command like `set <portlist> [src|dst] ip [<ipaddr>|random]`?

I am aware the `rnd` page could be used to achieve this, but following what's been discussed in this PR: https://github.com/pktgen/Pktgen-DPDK/pull/340, in ixgbe (and others) NICs the "packet header creation->`rnd`" pipeline makes the checksum calculation wrong, whereas this proposed solution would instead be implemented in the packet header creation. 

This also makes it generally easier, as the packet index to randomize the source IP address can be different (e.g., IPv4 v.s. IPv6), the number of indexes in the rnd table vary (2 indexes for IPv4 v.s. 4 indexes for IPv6), and we'd be saving those entries in the table.

For instance, instead of doing
```c
ipv4->src_addr = htonl(pkt->ip_src_addr.addr.ipv4.s_addr);
```
We could have
```c
if (!is_src_ip_random)
    ipv4->src_addr = htonl(pkt->ip_src_addr.addr.ipv4.s_addr);
else
    ipv4->src_addr = htonl(get_rand_u32());
```

This feature could later be expanded to e.g. specifying a country and generating IP addresses of that country (e.g., through a country list from [here](https://lite.ip2location.com/ip-address-ranges-by-country?lang=en_US)), so that firewalls can be tested in more detail.

(similar arguments for the source port)

Let me know if this would be an welcome addition! I could work on it :)

**Comment by pktgen** [comment]
Hi

I think it is a good idea and need to make sure the IP address generated is a valid IP address. The IP generator also needs to be pretty fast to maintain performance. The idea of using the country list is also a reasonable for the user. If you would like to add the support and create a PR it would be great.

**Comment by PedroChaparro123** [comment]
Cool!

I think I'll start with a simple `generate_random_ip()` that naively randomizes, and we can then build on top of it/change it to have fancier options like the user specifying a country/list of countries/set of IPs for IPs to be sampled from.

> I think it is a good idea and need to make sure the IP address generated is a valid IP address.

By valid, are you referring to non-reserved IP addresses (i.e., the generated IPs must not be on [this Reserved IP addresses list](https://en.wikipedia.org/wiki/Reserved_IP_addresses))? 
Doing some back-of-the-envelope math, only around 14% of all the IPs that can be generated are reserved, so I was thinking that maybe it would be worth it to not check for IP validity, as it could perhaps be a big overhead (never really did super efficient coding, so perhaps there's an easy way)?
Or we perhaps can start super naive and later add those checks (at least for the bigger intervals, 90% of the reserved IPs are distributed across two subnets)?

**Comment by PedroChaparro123** [comment]
Also, I believe adding separate `enable|disable` entries for the IP and for the port would make more sense and be easier than on a `set` command, as this would be something that would be changing on every packet and not a concrete value that is set (as e.g. setting the Ack number). 

I'd then add flags like `is_src_ip_random`/`is_src_port_random` which would be set based on the enables, and be used to decide to use either the default/user-supplied IP address through the `set` command, or a random one.

Do you agree?

**Comment by pktgen** [comment]
For the valid IP addresses lets not valid them and just use the random addresses as reserved addresses could be something someone wants to test.

The enable/disable commands would be fine as they are used per port as a type of mode flag. All of the modes should be listed in the 'Port:Flags' line per port. If you add a new mode it needs to show up in the 'Port:Flags' line.

Be careful to exclude TX packets like the ARP response from a remote ARP request packet. Also you need to make sure the random IP source address mode is only used on packets from the single packet mode. The range, pcap, rnd and sequence modes have IP addresses that are fixed values or already being changed.

I did not fully follow the `is_src_ip_random / is_src_port_random` flags. I see the need for `is_src_ip_random` flag, but the `is_src_port_random` I do not understand this flag.

Thanks

**Comment by PedroChaparro123** [comment]
> For the valid IP addresses lets not valid them and just use the random addresses as reserved addresses could be something someone wants to test.

Sounds good! :D

> The enable/disable commands would be fine as they are used per port as a type of mode flag. All of the modes should be listed in the 'Port:Flags' line per port. If you add a new mode it needs to show up in the 'Port:Flags' line.

Got it. Wasn't aware of this, so thanks for mentioning it.

> Be careful to exclude TX packets like the ARP response from a remote ARP request packet.

I see. Actually, I've only used Pktgen exclusively for Tx, never having processed any received packets. Can you clarify how "response" packets are generated from "request" packets? Having had a look, it wasn't fully obvious to me. It'd help me pinpoint the best place to add this logic.

> Also you need to make sure the random IP source address mode is only used on packets from the single packet mode. The range, pcap, rnd and sequence modes have IP addresses that are fixed values or already being changed.

Gotcha!

> I did not fully follow the is_src_ip_random / is_src_port_random flags. I see the need for is_src_ip_random flag, but the is_src_port_random I do not understand this flag.

Besides randomizing the source IP address, it'd also be convenient for me to randomize the source port, for similar reasons. So, I was thinking of having the same source IP address randomization logic for the port too. What do you think about this?

**Comment by pktgen** [comment]
The `PROCESS_INPUT_PKTS` flag is handled in app/pktgen.c in function `pktgen_packet_classify` the flag enables processing of ARP requests. The file `app/pktgen-arp.[ch]` is where code is located and allows the some to set and ARP request or ping the DUT with an ECHO request which is in another file.

I see the `is_src_port_random` is a reasonable addition.

**Comment by PedroChaparro123** [comment]
Gotcha! I will work on the PR and let you know once it's ready for review! :D

**Comment by PedroChaparro123** [comment]
Hi Keith!

Could you please have a look when you have the time?
Still not fully completed though.

**Comment by PedroChaparro123** [comment]
Sorry for the radio silence, I was out for the week. Thanks for having merged #342. 

I've just opened a new PR for the source port randomization, could you please have a look whenever you have the time? :)
Should be an easy one, as it's very similar to the source IP randomization PR.
